### ISSUE TITLE
Minus sign nisplace

### ISSUE THREAD

**Issue by lekarsenten** [saguiitay/HyperLogLog.net#3]
Hello, @saguiitay,
First of all - thank you for .net implementation.
Second - I think, you have misplaced "minus" sign in
src/HyperLogLog.net/HyperLogLog.net/HyperLogLog.cs@87 `dv = (int)(Math.Pow(-2, 32) * Math.Log(1 - dvEstimate / Pow2_32));`
According to this topic [http://algo.inria.fr/flajolet/Publications/FlFuGaMe07.pdf](url) it should be before Math.pow.

**Comment by saguiitay** [comment]
Seem's like you're right. I have a PR is a fix - I'll merge it

**Comment by saguiitay** [comment]
I've released a fix
